export const plantMockData = {
  SEQPLT19: "1",
  YEAR: "2019",
  PSTATABB: "LA",
  PNAME: "7-Mile Ridge Wind Project",
  ORISPL: "60814",
  OPRNAME: "Alaska Power and Telephone Co",
  OPRCODE: "219",
  UTLSRVNM: "Alaska Power and Telephone Co",
  UTLSRVID: "219",
  SECTOR: "Electric Utility",
  BANAME: "Alaska Miscellaneous",
  BACODE: "NA",
  NERC: "NA",
  SUBRGN: "AKMS",
  SRNAME: "ASCC Miscellaneous",
  FIPSST: "02",
  FIPSCNTY: "240",
  CNTYNAME: "Southeast Fairbanks",
  LAT: "63.210689",
  LON: "-143.247156",
  NUMUNT: "1",
  NUMGEN: "1",
  PLPRMFL: "WND",
  PLFUELCT: "WIND",
  NAMEPCAP: "1.8",
  UNHGSRC: "--",
};
